# Generated by Django 2.2.17 on 2021-01-27 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="name business"),
                ),
                (
                    "cpf_cnpj",
                    models.CharField(
                        max_length=14, unique=True, verbose_name="cpf or cnpj"
                    ),
                ),
                (
                    "presentation",
                    models.TextField(blank=True, verbose_name="presentation"),
                ),
                (
                    "type_user",
                    models.PositiveIntegerField(
                        choices=[(0, "FreeLancer"), (1, "Business")],
                        default=0,
                        verbose_name="type user",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.City",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "business",
            },
        ),
        migrations.CreateModel(
            name="BusinessCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_category",
                        to="common.Business",
                    ),
                ),
            ],
            options={
                "verbose_name": "business category",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
            ],
            options={
                "verbose_name": "category",
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategory",
                        to="common.Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "subcategory",
            },
        ),
        migrations.CreateModel(
            name="BusinessService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(verbose_name="price")),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("payment_hour", "Hour-based payment"),
                            ("payment_session", "Session-based payment"),
                            ("payment_daily", "Daily-based payment"),
                        ],
                        default="payment_hour",
                        max_length=50,
                        verbose_name="payment type",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_service",
                        to="common.Business",
                    ),
                ),
                (
                    "business_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.BusinessCategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "business service",
            },
        ),
        migrations.AddField(
            model_name="businesscategory",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.SubCategory"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="businesscategory",
            unique_together={("business", "subcategory")},
        ),
    ]
