# Generated by Django 2.2.17 on 2021-01-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessservice',
            name='price_hours',
        ),
        migrations.AddField(
            model_name='businessservice',
            name='payment_type',
            field=models.CharField(choices=[('payment_hour', 'Hour-based payment'), ('payment_session', 'Session-based payment'), ('payment_daily', 'Daily-based payment')], default='payment_hour', max_length=50, verbose_name='payment type'),
        ),
        migrations.AddField(
            model_name='businessservice',
            name='price',
            field=models.FloatField(default=0, verbose_name='price'),
            preserve_default=False,
        ),
    ]
