# Generated by Django 2.2.17 on 2020-12-06 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="description",
        ),
    ]
