# Generated by Django 2.2.17 on 2020-12-06 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subcategory",
            options={"verbose_name": "subcategory"},
        ),
        migrations.AlterUniqueTogether(
            name="businesscategory",
            unique_together={("business", "subcategory")},
        ),
    ]
