# Generated by Django 2.2.17 on 2020-12-06 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_auto_20201206_0040"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessservice",
            name="business_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="business_category",
                to="common.BusinessCategory",
            ),
        ),
    ]
