# Generated by Django 2.2.17 on 2020-12-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_auto_20201205_2144"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="cpf_cnpj",
            field=models.CharField(
                max_length=14, unique=True, verbose_name="description"
            ),
        ),
    ]
