# Generated by Django 2.2.17 on 2020-12-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_auto_20201205_2314"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="presentation",
            field=models.TextField(blank=True, verbose_name="presentation"),
        ),
    ]
