# Generated by Django 2.2.17 on 2020-12-05 23:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_auto_20201205_2316"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="id",
        ),
        migrations.AddField(
            model_name="business",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="UUID",
            ),
        ),
    ]
