# Generated by Django 2.2.17 on 2021-01-29 16:09

from django.db import migrations, models
import rookly.storages


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                null=True,
                storage=rookly.storages.AvatarUserMediaStorage(),
                upload_to="",
                verbose_name="photo user",
            ),
        ),
    ]
