# Generated by Django 2.2.18 on 2021-02-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="cpf",
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
