version: 2.1
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    docker:
      - image: cimg/python:3.6.10
        environment:
          DATABASE_URL: postgresql://root@localhost/rookly?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: rookly
    environment:
      SECRET_KEY: SK
      DEFAULT_DATABASE: postgres://root@localhost:5432/rookly
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Run install pipenv
          command: |
            pip install pipenv flake8
      - run:
          name: Run install packages
          command: |
            pipenv install
      - run:
          name: check pep8
          command: |
            flake8
      - run:
          name: Run django migrations
          command: |
            pipenv run python manage.py migrate
      - run:
          name: Run django collectstatic
          command: |
            pipenv run python manage.py collectstatic --noinput
      - run:
          name: Run django tests
          command: |
            pipenv run python manage.py test
